### ISSUE TITLE
Depends on a module hidden from PAUSE; URI::_generic

### ISSUE THREAD

**Issue by bleargh45** [rjbs/URI-cpan#1]
`URI::cpan` as distributed, depends on `URI::_generic`.  Unfortunately, that module is hidden from PAUSE, making it difficult to bootstrap `URI::cpan` using a command like `cpm install --local-lib-contained=/deps` as the dependency in non-resolvable.

Would be happy to submit an MR to address this, but wanted to ask first how you would prefer that to be laid out... I see that you are using DZil to do your packaging, including your dependency list.  Was unsure if an update to the `dist.ini` to indicate that the distribution depends on the `URI` distribution would be considered reasonable, or whether you had some other preferred way to help indicate the distribution that the (hidden) dependency resides in.

**Comment by rjbs** [comment]
Heya, I have just gone ahead and fixed this.  It seemed certain to be faster to just do it.  I didn't do anything interesting other than what you'll now see in the git history.

Thanks for bringing this to my attention.

**Comment by bleargh45** [comment]
Thank you!  Works like a charm!
