### ISSUE TITLE
URI-cpan-1.008 requires Perl 5.12

### ISSUE THREAD

**Issue by nanto** [rjbs/URI-cpan#2]
From URI-cpan-1.008, Perl 5.12 is required: https://metacpan.org/release/RJBS/URI-cpan-1.008/source/Makefile.PL#L17. Is this change intentional?

This change breaks tests on Perl 5.8 / 5.10 of Perl-Critic: Perl-Critic/Perl-Critic#973.

**Comment by rjbs** [comment]
This change is intentional.  The stated policy in this library is:
> This library should run on perls released even a long time ago. It should work on any version of perl released in the last five years.
> 
> Although it may work on older versions of perl, no guarantee is made that the minimum required version will not be increased. The version may be increased for any reason, and there is no promise that patches will be accepted to lower the minimum required perl.

Perl 5.12.0 was released nearly 12 years ago.  I do not plan to expend effort supporting very old versions of Perl.

**Comment by nanto** [comment]
I got it. Thank you!
